-- V1 — Initial Schema for Task Management Application

-- USERS
CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    email       VARCHAR(100) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    first_name  VARCHAR(50),
    last_name   VARCHAR(50),
    avatar      VARCHAR(255),
    role        VARCHAR(20)  NOT NULL DEFAULT 'ROLE_USER',
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

-- PROJECTS
CREATE TABLE projects (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    description   TEXT,
    key           VARCHAR(10)  NOT NULL UNIQUE,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    owner_id      BIGINT       NOT NULL REFERENCES users(id),
    task_counter  INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP
);

-- PROJECT MEMBERS
CREATE TABLE project_members (
    project_id BIGINT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    PRIMARY KEY (project_id, user_id)
);

-- TASKS
CREATE TABLE tasks (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_number      VARCHAR(20)  NOT NULL,
    title            VARCHAR(200) NOT NULL,
    description      TEXT,
    status           VARCHAR(20)  NOT NULL DEFAULT 'TODO',
    priority         VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    type             VARCHAR(20)  NOT NULL DEFAULT 'TASK',
    project_id       BIGINT       NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    assignee_id      BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    reporter_id      BIGINT       NOT NULL REFERENCES users(id),
    due_date         DATE,
    estimated_hours  INT,
    logged_hours     INT          NOT NULL DEFAULT 0,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP
);

CREATE INDEX idx_tasks_project  ON tasks(project_id);
CREATE INDEX idx_tasks_assignee ON tasks(assignee_id);
CREATE INDEX idx_tasks_status   ON tasks(status);

-- COMMENTS
CREATE TABLE comments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    TEXT   NOT NULL,
    task_id    BIGINT NOT NULL REFERENCES tasks(id)   ON DELETE CASCADE,
    author_id  BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX idx_comments_task ON comments(task_id);

-- TASK ACTIVITIES (audit log)
CREATE TABLE task_activities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT      NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users(id),
    action      VARCHAR(50) NOT NULL,
    field_name  VARCHAR(50),
    old_value   VARCHAR(255),
    new_value   VARCHAR(255),
    created_at  TIMESTAMP
);

CREATE INDEX idx_activities_task ON task_activities(task_id);
