-- ============================================================
-- V2 — Phase 2 Schema: Sprints, Labels, Time, Attachments,
--       Notifications, RefreshTokens, ProjectMemberRoles
-- ============================================================

-- REFRESH TOKENS
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token       VARCHAR(512) NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  TIMESTAMP    NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_refresh_user ON refresh_tokens(user_id);

-- PROJECT MEMBERS EXTENDED (role-aware)
CREATE TABLE project_members_ext (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT      NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
    role        VARCHAR(20) NOT NULL DEFAULT 'EDITOR',
    joined_at   TIMESTAMP,
    UNIQUE (project_id, user_id)
);
CREATE INDEX idx_pm_ext_project ON project_members_ext(project_id);

-- SPRINTS
CREATE TABLE sprints (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    goal        TEXT,
    status      VARCHAR(20)  NOT NULL DEFAULT 'PLANNED',
    project_id  BIGINT       NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    start_date  DATE,
    end_date    DATE,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);
CREATE INDEX idx_sprints_project ON sprints(project_id);

-- LABELS
CREATE TABLE labels (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL,
    color       VARCHAR(7)  NOT NULL DEFAULT '#4f8ef7',
    project_id  BIGINT      NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    UNIQUE (project_id, name)
);

-- TASK_LABELS (many-to-many)
CREATE TABLE task_labels (
    task_id  BIGINT NOT NULL REFERENCES tasks(id)  ON DELETE CASCADE,
    label_id BIGINT NOT NULL REFERENCES labels(id) ON DELETE CASCADE,
    PRIMARY KEY (task_id, label_id)
);

-- Add sprint_id and parent_id to tasks
ALTER TABLE tasks
    ADD COLUMN sprint_id     BIGINT REFERENCES sprints(id) ON DELETE SET NULL,
    ADD COLUMN parent_id     BIGINT REFERENCES tasks(id)   ON DELETE SET NULL,
    ADD COLUMN story_points  INT,
    ADD COLUMN rank_order    INT NOT NULL DEFAULT 0;

CREATE INDEX idx_tasks_sprint ON tasks(sprint_id);
CREATE INDEX idx_tasks_parent ON tasks(parent_id);

-- TIME ENTRIES
CREATE TABLE time_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id     BIGINT      NOT NULL REFERENCES tasks(id)  ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL REFERENCES users(id),
    minutes     INT         NOT NULL,
    log_date    DATE        NOT NULL,
    description VARCHAR(500),
    created_at  TIMESTAMP
);
CREATE INDEX idx_time_task ON time_entries(task_id);
CREATE INDEX idx_time_user ON time_entries(user_id);

-- ATTACHMENTS
CREATE TABLE attachments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name  VARCHAR(255) NOT NULL,
    stored_name    VARCHAR(255) NOT NULL,
    content_type   VARCHAR(100),
    file_size      BIGINT,
    task_id        BIGINT       NOT NULL REFERENCES tasks(id)  ON DELETE CASCADE,
    uploaded_by    BIGINT       NOT NULL REFERENCES users(id),
    created_at     TIMESTAMP
);
CREATE INDEX idx_attach_task ON attachments(task_id);

-- NOTIFICATIONS
CREATE TABLE notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type         VARCHAR(40)  NOT NULL,
    title        VARCHAR(255) NOT NULL,
    message      TEXT,
    entity_type  VARCHAR(30),
    entity_id    BIGINT,
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP
);
CREATE INDEX idx_notif_user ON notifications(user_id);
CREATE INDEX idx_notif_read ON notifications(is_read);
